#!/bin/sh
# http://d.hatena.ne.jp/kyubuns/20120106/1325866345
$*
if test $? -eq 0
then
        MESSAGE="complete!"
        P=0
else
        MESSAGE="error..."
        P=1
fi
growlnotify -t $MESSAGE -m "$*" -p $P
exit $P
