#!/bin/sh

play()
{
  osascript -e 'tell app "iTunes" to open location "'${1}'"'
  echo "play [ ${2} ]"
}

case $1 in
  stop)
    osascript -e 'tell app "iTunes" to stop'
    echo 'iTunes stop.'
  ;;
  help)
    echo "Usage: $0 {|help|stop|jazz|goa}"
    exit 1
  ;;
  goa)
    play 'http://uwstream2.somafm.com:8854' 'Suburbs of Goa'
  ;;
  jazz)
    play 'http://xstream1.somafm.com:8606' 'Sonic Universe'
  ;;
  *)
    play 'http://xstream1.somafm.com:8070' 'indie pop rocks'
  ;;
esac
